DefaultContentLanguage = "de"
Paginate = 9
SectionPagesMenu = "main"
baseURL = "/"
languageCode = "de-ch"
theme = "gohugo-theme-ananke"
title = "Family Schmid goes Canada"
[params]
description = "Blog über die Erlebnisse von der Familie Schmid in Kanada"
featured_image = "/images/header.jpg"
recent_posts_number = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
