---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: https://canada.yux.ch/.netlify/functions/post_published
sections:
- type: directory
  path: content/post
  label: Blog Posts
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - blog-post
upload_dir: canada-blog
public_path: https://res.cloudinary.com/yux/image/upload/w_auto,dpr_auto,c_scale,f_auto,q_auto
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
instant_preview: true
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.54.0
