backend:
  name: git-gateway
  branch: master

media_folder: "content/blog-images"
public_folder: "/blog-images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Intro", name: "intro", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Text", name: "body", widget: "markdown"}
